server:
  port: 8080

spring:
  application:
    name: osint-backend
  
  profiles:
    active: dev

logging:
  level:
    osint: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info

