classDiagram

direction TB

class ApiKeyRepository {
    <<interface>>
}
class EntityFindingRepository {
    <<interface>>
}
class EntityRepository {
    <<interface>>
}
class NotificationPreferencesRepository {
    <<interface>>
}
class NotificationRepository {
    <<interface>>
}
class PasswordResetTokenRepository {
    <<interface>>
}
class RefreshTokenRepository {
    <<interface>>
}
class RoleRepository {
    <<interface>>
}
class ScanLogRepository {
    <<interface>>
}
class ScanProviderRepository {
    <<interface>>
}
class ScanRepository {
    <<interface>>
}
class ScanResultRepository {
    <<interface>>
}
class ScanTargetRepository {
    <<interface>>
}
class UserRepository {
    <<interface>>
}
